-- Rafael Alcalde Azpiazu - 01 Feb 2018
-- Facultade de Informática da Coruña - Universidade da Coruña
--
-- This file gets the result of the parser and converts it in Freeciv map file

-- Get the parse table and translate it into a Freeciv map file
translate = (output, file, width, height, terrain, startpos) ->
  -- SCENARIO
  scenario = "[scenario]\nis_scenario=TRUE\nname=_(\"#{output}\")\n"
  scenario ..= "description=_(\"This map has generated by clingo ASP.\")\n"
  scenario ..= "players=TRUE\n\n"
  -- SAVEFILE
  savefile = '[savefile]\noptions=" +version2"\nversion=20\nreason="Scenario"\n'
  savefile ..= 'rulesetdir="classic"\nimprovement_size=68\nimprovement_vector=\n'
  savefile ..= '"Airport","Aqueduct","Bank","Barracks","Barracks II",'
  savefile ..= '"Barracks III","Cathedral","City Walls","Coastal Defense",'
  savefile ..= '"Colosseum","Courthouse","Factory","Granary","Harbour",'
  savefile ..= '"Hydro Plant","Library","Marketplace","Mass Transit",'
  savefile ..= '"Mfg. Plant","Nuclear Plant","Offshore Platform","Palace",'
  savefile ..= '"Police Station","Port Facility","Power Plant","Recycling Center",'
  savefile ..= '"Research Lab","SAM Battery","SDI Defense","Sewer System",'
  savefile ..= '"Solar Plant","Space Component","Space Module","Space Structural",'
  savefile ..= '"Stock Exchange","Super Highways","Supermarket","Temple",'
  savefile ..= '"University","Apollo Program","A.Smith\'s Trading Co.","Colossus",'
  savefile ..= '"Copernicus\' Observatory","Cure For Cancer","Darwin\'s Voyage",'
  savefile ..= '"Eiffel Tower","Great Library","Great Wall","Hanging Gardens",'
  savefile ..= '"Hoover Dam","Isaac Newton\'s College","J.S. Bach\'s Cathedral",'
  savefile ..= '"King Richard\'s Crusade","Leonardo\'s Workshop","Lighthouse",'
  savefile ..= '"Magellan\'s Expedition","Manhattan Project",'
  savefile ..= '"Marco Polo\'s Embassy","Michelangelo\'s Chapel","Oracle",'
  savefile ..= '"Pyramids","SETI Program","Shakespeare\'s Theatre",'
  savefile ..= '"Statue of Liberty","Sun Tzu\'s War Academy","United Nations",'
  savefile ..= '"Women\'s Suffrage","Coinage"\ntechnology_size=88\n'
  savefile ..= 'technology_vector="A_NONE","Advanced Flight","Alphabet",'
  savefile ..= '"Amphibious Warfare","Astronomy","Atomic Theory","Automobile",'
  savefile ..= '"Banking","Bridge Building","Bronze Working","Ceremonial Burial",'
  savefile ..= '"Chemistry","Chivalry","Code of Laws","Combined Arms",'
  savefile ..= '"Combustion","Communism","Computers","Conscription",'
  savefile ..= '"Construction","Currency","Democracy","Economics","Electricity",'
  savefile ..= '"Electronics","Engineering","Environmentalism","Espionage",'
  savefile ..= '"Explosives","Feudalism","Flight","Fusion Power",'
  savefile ..= '"Genetic Engineering","Guerilla Warfare","Gunpowder",'
  savefile ..= '"Horseback Riding","Industrialization","Invention","Iron Working",'
  savefile ..= '"Labor Union","Laser","Leadership","Literacy","Machine Tools",'
  savefile ..= '"Magnetism","Map Making","Masonry","Mass Production","Mathematics",'
  savefile ..= '"Medicine","Metallurgy","Miniaturization","Mobile Warfare",'
  savefile ..= '"Monarchy","Monotheism","Mysticism","Navigation","Nuclear Fission",'
  savefile ..= '"Nuclear Power","Philosophy","Physics","Plastics","Polytheism",'
  savefile ..= '"Pottery","Radio","Railroad","Recycling","Refining",'
  savefile ..= '"Refrigeration","Robotics","Rocketry","Sanitation","Seafaring",'
  savefile ..= '"Space Flight","Stealth","Steam Engine","Steel","Superconductors",'
  savefile ..= '"Tactics","The Corporation","The Republic","The Wheel","Theology",'
  savefile ..= '"Theory of Gravity","Trade","University","Warrior Code","Writing"\n'
  savefile ..= 'activities_size=21\nactivities_vector="Idle","Pollution",'
  savefile ..= '"Unused Road","Mine","Irrigate","Fortified","Fortress","Sentry",'
  savefile ..= '"Unused Railroad","Pillage","Goto","Explore","Transform","Unused",'
  savefile ..= '"Unused Airbase","Fortifying","Fallout","Unused Patrol","Base",'
  savefile ..= '"Road","Convert"\ntrait_size=3\ntrait_vector="Expansionist",'
  savefile ..= '"Trader","Aggressive"\nspecials_size=6\nspecials_vector='
  savefile ..= '"Irrigation","Mine","Pollution","Hut","Farmland","Fallout"\n'
  savefile ..= 'bases_size=4\nbases_vector="Fortress","Airbase","Buoy","Ruins"\n'
  savefile ..= 'roads_size=3\nroads_vector="Road","Railroad","River"\n\n'
  -- RANDOM
  random = '[random]\nsaved=FALSE\n\n'
  -- SCRIPT
  script = '[script]\ncode=$$\nvars=$$\n\n'
  -- SETTINGS
  settings = '[settings]\nset={"name","value","gamestart"\n"aqueductloss",0,0\n'
  settings ..= '"diplchance",3,3\n"endturn",410,410\n"foodbox",10,10\n'
  settings ..= '"generator","SCENARIO","SCENARIO"\n"gold",75,75\n"maxplayers",5,5\n'
  settings ..= '"mapsize","XYSIZE","XYSIZE"\n"minplayers",1,1\n"sciencebox",80,80\n'
  settings ..= '"spacerace",FALSE,FALSE\n"startunits","ccxww","ccxww"\n'
  settings ..= '"techlevel",3,3\n"topology","",""\n'
  settings ..= "\"xsize\",#{width},#{width}\n\"ysize\",#{height},#{height}\n}\n"
  settings ..= 'set_count=16\ngamestart_valid=FALSE\n\n'
  -- GAME
  game = '[game]\nversion=20500\nserver_state="S_S_INITIAL"\nmeta_patches="none"\n'
  game ..= "meta_usermessage=TRUE\nmeta_message=\"Scenario: #{output}\"\n"
  game ..= 'meta_server="http://meta.freeciv.org/metaserver.php"\nid=""\n'
  game ..= 'serverid=""\nskill_level=5\nphase_mode=0\nphase_mode_stored=0\n'
  game ..= 'phase=0\nscoreturn=20\ntimeoutint=0\ntimeoutintinc=0\ntimeoutinc=0\n'
  game ..= 'timeoutincmult=1\ntimeoutcounter=1\nturn=0\nyear=-4000\n'
  game ..= 'year_0_hack=FALSE\nglobalwarming=0\nheating=0\nwarminglevel=8\n'
  game ..= 'nuclearwinter=0\ncooling=0\ncoolinglevel=8\nsave_players=FALSE\n'
  game ..= 'save_known=FALSE\n\n'
  -- MAP
  map = '[map]\nhave_huts=TRUE\n'

  df = io.open file, "w+"

  -- Write headers
  df\write scenario
  df\write savefile
  df\write random
  df\write settings
  df\write game
  df\write map

  -- Write map
  for i = 1, width do
    df\write string.format "t%04i=\"", (i-1)
    for j = 1, height do
      value = terrain[i][j]
      switch value
        when 'water'
          df\write ":"
        when 'grass'
          df\write "g"
    df\write "\"\n"

  -- Write start positions
  df\write "startpos_count=#{#startpos}\nstartpos={\"x\",\"y\",\"exclude\",\"nations\"\n"
  for pos in *startpos do
    df\write "#{pos.x},#{pos.y},FALSE,\"\"\n"
  df\write "}\n"

  -- Write b00 layer
  for i = 1, width do
    df\write string.format "b00_%04i=\"", (i-1)
    for j = 1, height do
      df\write "0"
    df\write "\"\n"

  -- Write r00 layer (resources)
  for i = 1, width do
    df\write string.format "r00_%04i=\"", (i-1)
    for j = 1, height do
      df\write "0"
    df\write "\"\n"

  df\flush!
  df\close!

{ :translate}
